# Generated by Django 5.2.16 on 2026-07-31 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acao', models.CharField(choices=[('criacao', 'Criação'), ('enquadramento', 'Enquadramento'), ('envio_documento', 'Envio de documento'), ('analise_ia', 'Análise por IA'), ('consulta_compliance', 'Consulta de compliance'), ('transicao_estado', 'Transição de estado'), ('aprovacao', 'Aprovação'), ('reprovacao', 'Reprovação'), ('dispensa', 'Dispensa (waiver)'), ('download', 'Download de documento')], max_length=32, verbose_name='ação')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('object_id', models.PositiveBigIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'evento de auditoria',
                'verbose_name_plural': 'eventos de auditoria',
                'ordering': ('-data_hora',),
            },
        ),
    ]
