# Generated by Django 5.2.16 on 2026-07-31 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoauditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Nulo quando a ação foi executada pelo sistema (tarefa assíncrona).', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddIndex(
            model_name='eventoauditoria',
            index=models.Index(fields=['content_type', 'object_id'], name='auditoria_e_content_4e349f_idx'),
        ),
    ]
