# Generated by Django 5.2.16 on 2026-07-31 18:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrapartes', '0001_initial'),
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraEnquadramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(help_text='Texto do guia. Ex.: "Evento até R$ 5.000,00".', max_length=200, verbose_name='critério')),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Inclusivo.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor mínimo')),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Inclusivo. Em branco, não há limite superior.', max_digits=14, null=True, verbose_name='valor máximo')),
                ('exige_triagem', models.BooleanField(default=True, verbose_name='triagem CRM')),
                ('exige_due_diligence', models.BooleanField(default=False, verbose_name='compliance (DD)')),
                ('exige_risco_credito', models.BooleanField(default=False, verbose_name='risco / crédito')),
                ('exige_juridico', models.BooleanField(default=False, verbose_name='jurídico ASA/Genial')),
                ('exige_assinaturas', models.BooleanField(default=False, verbose_name='assinaturas')),
                ('exige_boletagem', models.BooleanField(default=True, verbose_name='boletagem e liquidação')),
                ('waiver', models.BooleanField(default=False, help_text='Dispensa documentação e todas as etapas de aprovação. Compras até R$ 10.000,00, conforme o guia.')),
                ('implementada', models.BooleanField(default=False, help_text='Marcada apenas nos enquadramentos liberados para uso. O MVP roda um por vez (AGENTS.md D11).')),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'regra de enquadramento',
                'verbose_name_plural': 'regras de enquadramento',
                'ordering': ('tipo_operacao__nome', 'valor_minimo'),
            },
        ),
        migrations.CreateModel(
            name='TipoOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de operação',
                'verbose_name_plural': 'tipos de operação',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor total')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_documentos', 'Aguardando documentos'), ('em_aprovacao', 'Em aprovação'), ('aguardando_assinatura', 'Aguardando assinatura'), ('assinada', 'Assinada'), ('concluida', 'Concluída'), ('reprovada', 'Reprovada'), ('dispensada', 'Dispensada (waiver)')], default='rascunho', max_length=32)),
                ('motivo_reprovacao', models.TextField(blank=True, verbose_name='motivo da reprovação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('contraparte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operacoes', to='contrapartes.contraparte')),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('regra', models.ForeignKey(blank=True, help_text='Definido no momento do enquadramento; congelado depois disso.', null=True, on_delete=django.db.models.deletion.PROTECT, to='operacoes.regraenquadramento', verbose_name='enquadramento')),
                ('tipo_operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacoes.tipooperacao')),
            ],
            options={
                'verbose_name': 'operação',
                'verbose_name_plural': 'operações',
                'ordering': ('-data_criacao',),
            },
        ),
        migrations.AddField(
            model_name='regraenquadramento',
            name='tipo_operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras', to='operacoes.tipooperacao'),
        ),
        migrations.CreateModel(
            name='EtapaAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('triagem', '1. Triagem de documentos (CRM)'), ('due_diligence', '2. Due diligence (Compliance)'), ('risco_credito', '3. Pesquisa de crédito (Risco/Crédito)'), ('juridico', '4. Revisão jurídica e vigência (Jurídico ASA/Genial)'), ('assinaturas', '5. Upload para assinatura (Clube)'), ('envio_nf', '6. Envio de NFs para liquidação (Clube)'), ('boletagem', '7. Boletagem (ASA/CRM)'), ('liquidacao', '8. Liquidação (Genial)')], max_length=32)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em análise'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada'), ('dispensada', 'Não aplicável'), ('registrada_externamente', 'Registrada externamente')], default='pendente', max_length=32)),
                ('parecer', models.TextField(blank=True, help_text='Obrigatório para aprovar ou reprovar. Registra a decisão humana.')),
                ('data_decisao', models.DateTimeField(blank=True, null=True, verbose_name='data da decisão')),
                ('decidida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='operacoes.operacao')),
            ],
            options={
                'verbose_name': 'etapa de aprovação',
                'verbose_name_plural': 'etapas de aprovação',
                'ordering': ('operacao', 'id'),
                'unique_together': {('operacao', 'etapa')},
            },
        ),
        migrations.CreateModel(
            name='ExigenciaDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrigatorio', models.BooleanField(default=True)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentos.tipodocumento')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exigencias', to='operacoes.regraenquadramento')),
            ],
            options={
                'verbose_name': 'exigência documental',
                'verbose_name_plural': 'exigências documentais',
                'unique_together': {('regra', 'tipo_documento')},
            },
        ),
    ]
