# Generated by Django 5.2.16 on 2026-07-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('escopo', models.CharField(choices=[('cadastral', 'Cadastral (contraparte)'), ('operacional', 'Operacional (operação)')], max_length=16)),
                ('kit_cadastral_pj', models.BooleanField(default=False, help_text='Documentação base exigida de toda contraparte pessoa jurídica.', verbose_name='compõe o Kit Cadastral PJ')),
                ('dias_validade', models.PositiveIntegerField(blank=True, help_text='Prazo de vigência a partir da data de emissão. Ex.: comprovante de endereço, 90 dias. Em branco, o documento não vence.', null=True, verbose_name='validade (dias)')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'tipos de documento',
                'ordering': ('escopo', 'nome'),
            },
        ),
    ]
