# Generated by Django 5.2.16 on 2026-08-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_carga_exigencias_cadastrais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exigenciacadastral',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
