# Generated by Django 5.2.16 on 2026-07-31 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contraparte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('pf', 'Pessoa física'), ('pj', 'Pessoa jurídica')], max_length=2, verbose_name='tipo de pessoa')),
                ('nome', models.CharField(help_text='Razão social, no caso de pessoa jurídica.', max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200)),
                ('documento', models.CharField(help_text='Somente dígitos.', max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('parte_relacionada', models.BooleanField(default=False, help_text='Marque se houver vínculo com o Fundo, o Clube ou a gestora. Gera alerta para o Compliance; não altera a alçada.')),
                ('ativa', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'contraparte',
                'verbose_name_plural': 'contrapartes',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='DocumentoCadastral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='cadastral/%Y/%m/')),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('processando', 'Processando'), ('analisado', 'Analisado'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('falha_analise', 'Falha na análise')], default='enviado', max_length=16)),
                ('data_emissao', models.DateField(blank=True, help_text='Base para o cálculo de vigência. Pode vir da extração por IA.', null=True, verbose_name='data de emissão')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('contraparte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_cadastrais', to='contrapartes.contraparte')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentos.tipodocumento')),
            ],
            options={
                'verbose_name': 'documento cadastral',
                'verbose_name_plural': 'documentos cadastrais',
                'ordering': ('-data_envio',),
            },
        ),
    ]
