# Generated by Django 5.2.16 on 2026-08-04 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0008_pdf_convertido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contraparte',
            name='alterada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrapartes_alteradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contraparte',
            name='campos_alterados',
            field=models.CharField(blank=True, help_text='O que mudou na última edição. Só rótulos — nunca o conteúdo.', max_length=255, verbose_name='campos alterados'),
        ),
        migrations.AddField(
            model_name='contraparte',
            name='data_alteracao_cadastral',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última alteração cadastral'),
        ),
    ]
